version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Cloudrc2"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ezs43fu733jq"
s3_prefix = "Cloudrc2"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
confirm_changeset = true
