name: main
on: push
env:
  python_version: 3.9

jobs:
  test-infra:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

# everything below this is incorrect infrastructure  for what you are working with probably need SAM and Python test

      - name: Install pytest
        run: python -m pip install pytest
      - name: test GetFunction
        run: cd Desktop/cloud-r-c/cloudRC/GetFunction/app.py && python -m pytest && cd ../../../../
      - name: test PutFunction
        run: cd Desktop/could-r-c/cloudRC/PutFunction && python -m pytest && cd ../../../
            #
